include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    avoid_final_parameters: false
    sort_constructors_first: false
    avoid_function_literals_in_foreach_calls: false
    prefer_int_literals: false
    lines_longer_than_80_chars: false
    use_build_context_synchronously: false